jQuery(document).ready(function(){
    var jsFolder = "images/";
    if ( typeof html5Lightbox === "undefined" )
    {
        html5Lightbox = jQuery(".html5lightbox").html5lightbox({
            jsfolder:jsFolder
        });
    }
    jQuery("#amazingcarousel-6").amazingcarousel({
        jsfolder:jsFolder,
        width:300,
        height:300,
        interval:3000,
        itembottomshadowimagetop:99,
        random:false,
        direction:"horizontal",
        //arrowheight:28,
        itembackgroundimagewidth:100,
        skin:"Navigator",
        responsive:true,
        bottomshadowimage:"bottomshadow-110-95-0.png",
        navstyle:"bullets",
        enabletouchswipe:true,
        backgroundimagetop:-40,
        arrowstyle:"always",
        bottomshadowimagetop:95,
        transitionduration:1000,
        hoveroverlayimage:"hoveroverlay-64-64-5.png",
        itembottomshadowimage:"itembottomshadow-100-98-3.png",
        showitembottomshadow:false,
        transitioneasing:"easeOutExpo",
        showitembackgroundimage:false,
        itembackgroundimage:"",
        playvideoimagepos:"center",
        circular:true,
        /*arrowimage:"arrows-28-28-0.png",*/
        showbottomshadow:false,
        screenquery:{
	mobile: {
		screenwidth: 770,
		visibleitems: 1
	}
},
        navimage:"bullet-12-12-1.png",
        itembackgroundimagetop:0,
        showbackgroundimage:false,
        showplayvideo:true,
        spacing:20,
        scrollitems:1,
        showhoveroverlay:true,
        scrollmode:"page",
        navdirection:"horizontal",
        itembottomshadowimagewidth:100,
        backgroundimage:"",
        //arrowwidth:28,
        pauseonmouseover:true,
        navmode:"page",
        arrowhideonmouseleave:1000,
        navwidth:12,
        navspacing:4,
        playvideoimage:"playvideo-64-64-0.png",
        visibleitems:2,
        navswitchonmouseover:false,
        bottomshadowimagewidth:110,
        autoplay:false,
        backgroundimagewidth:110,
        loop:0,
        navheight:12
    });
});